package mosis.streetsandtotems.ui.theme
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF006b5b)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF77f8de)
val md_theme_light_onPrimaryContainer = Color(0xFF00201a)
val md_theme_light_secondary = Color(0xFF4b635d)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFcde8e0)
val md_theme_light_onSecondaryContainer = Color(0xFF06201b)
val md_theme_light_tertiary = Color(0xFF446278)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFc7e6ff)
val md_theme_light_onTertiaryContainer = Color(0xFF001e30)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfafdfa)
val md_theme_light_onBackground = Color(0xFF191c1b)
val md_theme_light_surface = Color(0xFFfafdfa)
val md_theme_light_onSurface = Color(0xFF191c1b)
val md_theme_light_surfaceVariant = Color(0xFFdbe5e1)
val md_theme_light_onSurfaceVariant = Color(0xFF3f4946)
val md_theme_light_outline = Color(0xFF6f7976)
val md_theme_light_inverseOnSurface = Color(0xFFeff1ef)
val md_theme_light_inverseSurface = Color(0xFF2e3130)
val md_theme_light_inversePrimary = Color(0xFF58dbc2)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF58dbc2)
val md_theme_dark_onPrimary = Color(0xFF00382f)
val md_theme_dark_primaryContainer = Color(0xFF005144)
val md_theme_dark_onPrimaryContainer = Color(0xFF77f8de)
val md_theme_dark_secondary = Color(0xFFb1ccc4)
val md_theme_dark_onSecondary = Color(0xFF1c352f)
val md_theme_dark_secondaryContainer = Color(0xFF334c46)
val md_theme_dark_onSecondaryContainer = Color(0xFFcde8e0)
val md_theme_dark_tertiary = Color(0xFFabcbe5)
val md_theme_dark_onTertiary = Color(0xFF123348)
val md_theme_dark_tertiaryContainer = Color(0xFF2b4a5f)
val md_theme_dark_onTertiaryContainer = Color(0xFFc7e6ff)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF191c1b)
val md_theme_dark_onBackground = Color(0xFFe1e3e1)
val md_theme_dark_surface = Color(0xFF191c1b)
val md_theme_dark_onSurface = Color(0xFFe1e3e1)
val md_theme_dark_surfaceVariant = Color(0xFF3f4946)
val md_theme_dark_onSurfaceVariant = Color(0xFFbfc9c5)
val md_theme_dark_outline = Color(0xFF88938f)
val md_theme_dark_inverseOnSurface = Color(0xFF191c1b)
val md_theme_dark_inverseSurface = Color(0xFFe1e3e1)
val md_theme_dark_inversePrimary = Color(0xFF006b5b)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF006b5c)
val error = Color(0xFFba1b1b)